# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('fee', models.IntegerField(default=3000)),
            ],
        ),
    ]
