# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190312_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactForms',
        ),
    ]
