# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('scourse', models.CharField(max_length=30)),
                ('sphno', models.IntegerField(max_length=30)),
                ('sfee', models.IntegerField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrainLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tcourse', models.CharField(max_length=30)),
                ('texperiance', models.CharField(max_length=30)),
                ('tphno', models.IntegerField(max_length=30)),
            ],
        ),
    ]
